# Generated by Django 4.0.5 on 2022-06-16 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_modo_delete_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='editora',
        ),
    ]
