# Generated by Django 4.0.5 on 2022-06-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_remove_livro_editora'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='capa',
            field=models.ImageField(blank=True, upload_to='livros/capas/'),
        ),
    ]
