# Generated by Django 4.0.5 on 2022-06-16 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0006_livro_capa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Modo',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
