# Generated by Django 4.0.5 on 2022-06-11 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_rename_compras_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('1', 'Não Lido'), ('2', 'Lendo'), ('3', 'Lido')], max_length=1)),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='livro',
            name='valor',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.AddField(
            model_name='status',
            name='id_livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.livro'),
        ),
        migrations.AddField(
            model_name='status',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.usuario'),
        ),
    ]
